<?php
    $this->title = "Airport Management";
?>
<br/>


<form action="/airport/index.html" method="post">

    <div class="row">
        <div class="panel panel-primary">
            <div class="panel-heading">Airport List</div>
            <div class="panel-body">

                <div class="col-md-6">
                    <select name="country" class="form-control">
                        <option>--chọn--</option>
                        <?php foreach($countries as $c){ ?>
                            <option <?php echo $country==$c['country']?"selected":""; ?> value="<?= $c['country']; ?>" ><?= $c['country']; ?></option>
                        <?php }?>
                    </select>
                </div>
                <div class="col-md-6">
                <button type="submit" class="btn btn-danger"><i class="fa fa-search fa-lg"></i> Show</button>
                    <a href="/airport/add.html" class="btn btn-default"><i class="fa fa-plus fa-lg"></i> Add New</a>
                </div>
                <br/>
                <hr/>
                <?php if (!empty($country)){ ?>
                    <table class="table table-striped table-bordered table-hover table-condensed">
                        <thead>
                        <tr>
                            <th>No.</th>
                            <th>Code</th>
                            <th>Name</th>
                            <th>City</th>
                            <th>State</th>
                            <th>Country</th>
                            <th>Action</th>
                        </tr>
                        </thead>
                        <tbody>
                        <?php $i = 0; foreach($allAirport as $m) { ?>
                            <tr>
                                <td><?php echo ++$i; ?></td>
                                <td><?= $m->code; ?></td>
                                <td><?= $m->name; ?></td>
                                <td><?= $m->city; ?></td>
                                <td><?= $m->state; ?></td>
                                <td><?= $m->country; ?></td>
                                <td class="text-center">
                                    <a class="del"
                                       href="#"
                                       data-url="/airport/delete/<?= $m->code; ?>"
                                       data-airportname="<?= $m->name; ?>"
                                    >
                                        <i class="fa fa-trash"></i></a></td>
                                </td>
                            </tr>
                        <?php } ?>
                        </tbody>
                    </table>
                <?php } ?>
            </div>
        </div>
    </div>

</form>


<div id="dialog" class="modal fade" tabindex="-1" role="dialog">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title">Xóa sân bay</h4>
            </div>
            <div class="modal-body">
                <p id="msg"></p>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                <button type="button" class="btn btn-primary">Save changes</button>
            </div>
        </div><!-- /.modal-content -->
    </div><!-- /.modal-dialog -->
</div><!-- /.modal -->