<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title><?php echo $this->title; ?></title>

    <!-- Bootstrap -->
    <link rel="shortcut icon" href="favicon.ico">
    <link href='https://fonts.googleapis.com/css?family=Open+Sans:400,700,300' rel='stylesheet' type='text/css'>
    
    <!-- Animate.css -->
    <link rel="stylesheet" href="/css/animate.css">
    <!-- Icomoon Icon Fonts-->
    <link rel="stylesheet" href="/css/icomoon.css">
    <!-- Bootstrap  -->
    <link rel="stylesheet" href="/css/bootstrap.css">
    <!-- Superfish -->
    <link rel="stylesheet" href="/css/superfish.css">
    <!-- Magnific Popup -->
    <link rel="stylesheet" href="/css/magnific-popup.css">
    <!-- Date Picker -->
    <link rel="stylesheet" href="/css/bootstrap-datepicker.min.css">
    <!-- CS Select -->
    <link rel="stylesheet" href="/css/cs-select.css">
    <link rel="stylesheet" href="/css/cs-skin-border.css">
    
    <link rel="stylesheet" href="/css/style.css">
    <!-- Modernizr JS -->
    <script src="js/modernizr-2.6.2.min.js"></script>
    <link href="/css/loading.css" rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">

    <?php echo $css ;?>

  </head>
  <body>
    <div id="fh5co-wrapper">
    <div id="fh5co-page">
      <header id="fh5co-header-section" class="sticky-banner">
        <div class="container">
          <div class="nav-header">
            <a href="#" class="js-fh5co-nav-toggle fh5co-nav-toggle dark"><i></i></a>
            <h1 id="fh5co-logo"><a href="index.html"><i class="icon-airplane"></i>Travel</a></h1>
            <!-- START #fh5co-menu-wrap -->
            <nav id="fh5co-menu-wrap" role="navigation" class="navbar fixed-top">
              <ul class="sf-menu" id="fh5co-primary-menu">
                <li><a href="index.html">Home</a></li>
                <li>
                  <a href="vacation.html" class="fh5co-sub-ddown">Vacations</a>
                  <ul class="fh5co-sub-menu">
                    <li><a href="#">Family</a></li>
                    <li><a href="#">CSS3 &amp; HTML5</a></li>
                    <li><a href="#">Angular JS</a></li>
                    <li><a href="#">Node JS</a></li>
                    <li><a href="#">Django &amp; Python</a></li>
                  </ul>
                </li>
                <li class="active"><a href="flight.html">Flights</a></li>
                <li><a href="hotel.html">Hotel</a></li>
                <li><a href="car.html">Car</a></li>
                <li><a href="blog.html">Blog</a></li>
                <li><a href="contact.html">Contact</a></li>
                <?php if (! $this->app->isLogin()) { ?>
                  <li> <a href="/user/login.html">Login</a> </li>
                <?php } else { ?>
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><?php echo $this->app->getUser()->username; ?><span class="caret"></span></a>
                        <ul class="fh5co-sub-menu">
                            <li><a href="/user/logout.html">Logout</a></li>
                            <li><a href="#">Another action</a></li>
                            <li><a href="#">Something else here</a></li>
                            <li role="separator" class="divider"></li>
                            <li><a href="#">Separated link</a></li>
                        </ul>
                    </li>


                <?php } ?>
              </ul>
            </nav>
          </div>
        </div>
      </header>
                
        <!-- end:header-top -->
      
            <div class="container">
              <div class="row">

                  <?php echo $content; ?>
                
              </div>
            </div>
       
        
       


    <div class="panel panel-primary" id="loading"  style="display: none;">
        <div class="panel-heading">
            <h4 class="panel-title">Loading...</h4>
        </div>
        <div class="panel-body">
            <span id="loadingMsg">Đang tải dữ liệu vui lòng chờ giây lát.</span>
            <div id="imgLoading" ><img  src="/css/loading_red.gif"/></div>
        </div>
    </div>

    <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->

    <!-- JS of template -->
    <script src="js/jquery.min.js"></script>
    <!-- jQuery Easing -->
    <script src="js/jquery.easing.1.3.js"></script>
    <!-- Bootstrap -->
    <script src="js/bootstrap.min.js"></script>
    <!-- Waypoints -->
    <script src="js/jquery.waypoints.min.js"></script>
    <script src="js/sticky.js"></script>
    <!-- Stellar -->
    <script src="js/jquery.stellar.min.js"></script>
    <!-- Superfish -->
    <script src="js/hoverIntent.js"></script>
    <script src="js/superfish.js"></script>
    <!-- Magnific Popup -->
    <script src="js/jquery.magnific-popup.min.js"></script>
    <script src="js/magnific-popup-options.js"></script>
    <!-- Date Picker -->
    <script src="js/bootstrap-datepicker.min.js"></script>
    <!-- CS Select -->
    <script src="js/classie.js"></script>
    <script src="js/selectFx.js"></script>
    
    <!-- Main JS -->
    <script src="js/main.js"></script>
    <!--  End js template -->

    <script src="/js/jquery-3.3.1.min.js"></script>

      <!-- Include all compiled plugins (below), or include individual files as needed -->
    <script src="/js/bootstrap.min.js"></script>
    <?php echo $js ;?>
  </body>
</html>