<div class="row jumbotron">
                            <div class="card">
                                <div class="card-header" data-background-color="purple">
                                    <h4 class="title">Forgot Password</h4>
                                    <p class="category">Complete your profile </p>
                                </div>
                                <div class="card-content">
                                    <form action="/user/changePass" method="POST">
                                        <div class="row">
                                            <div class="col-md-3"></div>
                                            <div class="col-md-6">
                                                <div class="form-group label-floating">
                                                    <label class="control-label">Username</label>
                                                    <input type="password" class="form-control" name="username">
                                                </div>
                                            </div>
                                            
                                        </div>
                                        <div class="row">
                                            <div class="col-md-3"></div>
                                            <div class="col-md-6">
                                                <div class="form-group label-floating">
                                                    <label class="control-label">New Password</label>
                                                    <input type="password" class="form-control" name="newpass">
                                                </div>
                                            </div>
                                            
                                        </div>
                                        <div class="row">
                                            <div class="col-md-3"></div>
                                            <div class="col-md-6">
                                                <div class="form-group label-floating">
                                                    <label class="control-label">Confirm Password</label>
                                                    <input type="password" class="form-control" name="confirmpass">
                                                </div>
                                            </div>
                                            
                                        </div>
                                        <button type="submit" class="btn btn-primary pull-right">Edit Profile</button>
                                        <div class="clearfix"></div>
                                         <?php if ($error != "") { ?>
                                        <div class="alert alert-danger" role="alert"><?= $error; ?></div>
                                        <?php } ?>
                                        <?php if ($success != "") { ?>
                                        <div class="alert alert-success" role="alert"><?= $success; ?></div>
                                        <?php } ?>

                                    </form>
                                </div>
                            </div>
</div>