<br/>

<form method="post" action="/user/login.html">
<div class="row">
    <div class="col col-md-3"></div>
    <div class="col col-md-6">
        <div class="panel panel-primary">
            <div class="panel-heading">Login</div>
            <div class="panel-body">
                <div class="form-group">
                    <label for="exampleInputEmail1">Username</label>
                    <input type="text" class="form-control" id="txtUsername" name="username" placeholder="Username">
                </div>
                <div class="form-group">
                    <label for="exampleInputPassword1">Password</label>
                    <input type="password" class="form-control" id="txtPassword" name="password" placeholder="Password">
                </div>

                <div class="checkbox">
                    <label>
                        <input type="checkbox"> Remember me
                    </label>
                </div>
                <button type="submit" class="btn btn-primary">Login</button>
            </div>
        </div>

        <?php if ($error != "") { ?>
        <div class="alert alert-danger" role="alert"><?= $error; ?></div>
        <?php } ?>

    </div>
    <div class="col col-md-3"></div>
</div>
</form>
