<?php
    $this->title = "Trang quản lí khách hàng";
?>
<br/>

<div class="container">
    <form action="/customer/index.html" method="post">
    <div class="modal-content">
        <div class="row">
            <div class="panel panel-primary">
                <div class="panel-heading">Customer List</div>
                <div class="panel-body">

                    <div class="col-md-6">
                        <select name="company" class="form-control">
                            <option>--chọn--</option>
                            <?php foreach($companies as $c){ ?>
                                <option <?php echo $company==$c['company_id']?"selected":""; ?> value="<?= $c['company_id']; ?>" ><?= $c['company_id']; ?></option>
                            <?php }?>
                        </select>
                    </div>
                    <div class="col-md-6">
                    <button type="submit" class="btn btn-danger"><i class="fa fa-search fa-lg"></i> Show</button>
                        <a href="/customer/add.html" class="btn btn-default"><i class="fa fa-plus fa-lg"></i> Add New</a>
                        <input type="fa-search"/>
                        <button class="btn btn-default"><i class="fa fa-search fa-lg"></i></button>
                    </div>
                    <br/>
                    <hr/>
                    <?php if (!empty($company)){ ?>
                        <table class="table table-striped table-bordered table-hover table-condensed">
                            <thead>
                            <tr>
                                <th class="text-center">No</th>
                                <th  class="text-center">Id</th>
                                <th  class="text-center">User Id</th>
                                <th  class="text-center">Person Id</th>
                                <th  class="text-center">Deleted</th>
                                <th  class="text-center">Company ID</th>
                                <th  class="text-center">Sửa</th>
                                <th  class="text-center">Xóa</th>
                            </tr>
                            </thead>
                            <tbody>
                             <?php $i=0; foreach($allCustomer as $m) { ?>
                                <tr>
                                    <td><?php echo ++$i; ?></td>
                                    <td><?= $m->id; ?></td>
                                    <td><?= $m->user_id; ?></td>                                    
                                    <td><?= $m->person_id; ?></td>
                                    <td><?= $m->deleted; ?></td>
                                    <td><?= $m->company_id; ?></td>
                                    <td class="text-center"> <a class="del"
                                           href="/customer/edit/<?= $m->id; ?>"
                                        >
                                            <i class="fa fa-edit"></i></a></td></td>
                                    <td class="text-center">
                                       
                                        <a class="del"
                                           href="/customer/delete/<?= $m->id; ?>"
                                        >
                                            <i class="fa fa-trash"></i></a></td>
                                    </td>
                                </tr>
                            <?php } ?>
                            </tbody>
                        </table>
                    <?php } ?>
                </div>
            </div>
        </div>
    </div>
</form>
</div>



<div id="dialog" class="modal fade" tabindex="-1" role="dialog">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title">Xóa khách hàng</h4>
            </div>
            <div class="modal-body">
                <p id="msg"></p>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                <button type="button" class="btn btn-primary">Save changes</button>
            </div>
        </div><!-- /.modal-content -->
    </div><!-- /.modal-dialog -->
</div><!-- /.modal -->
